# This is a basic workflow to help you get started with Actions

name: Blob Upload reporting assets

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Upload KQL files to blob storage
      # make sure AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_SAS_TOKEN are set 
      - name: Azure CLI Action
        uses: Azure/cli@v1
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          KQL_PATH: notebooks/kql
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az storage blob sync -c $AZURE_STORAGE_CONTAINER -s notebooks/kql -d "$KQL_PATH"
